---
title: "R Notebook"
output: html_notebook
---


```{r}
rmat <- function(nrow, ncol, ...){
  matrix(rnorm(nrow * ncol, ...), nrow = nrow, ncol = ncol)
}

A <- rmat(1000, 10)
B <- rmat(11, 60)
X_true <- rmat(ncol(A), nrow(B))
Y <- A %*% X_true %*% B + rmat(nrow(A), ncol(B), sd = 0.02)
```

```{r}
solve(t(A) %*% A) %*% t(A) %*% Y %*% t(B) %*% solve(B %*% t(B))
```

```{r}
X_vec <- lm.fit(kronecker(t(B), A), as.vector(Y))$coefficients
tmp <- matrix(X_vec, nrow = ncol(A), ncol = nrow(B))
tmp[is.na(tmp)] <- 0
sum((Y - A %*% tmp %*% B)^2)
tmp
X_true
```
```{r}
QR <- qr(A)
PU_t <- qr(t(B))
Rinv <- backsolve(qr.R(QR), diag(nrow = ncol(A)))
Pinv <- t(backsolve(qr.R(PU_t), diag(nrow = nrow(B))))
qr.qy(PU_t, t(qr.qty(QR, Y)))

Rinv %*% (t(qr.Q(QR)) %*% Y %*% qr.Q(PU_t)) %*% Pinv


```


```{r, paged.print=FALSE}
I_A <- diag(nrow = ncol(A))
I_B <- diag(nrow = nrow(B))
bench::mark(
  normal = solve(t(A) %*% A) %*% t(A) %*% Y %*% t(B) %*% solve(B %*% t(B)),
  qr = {
    QR <- qr(A)
    PU_t <- qr(t(B))
    Rinv <- backsolve(qr.R(QR), I_A)
    Pinv <- t(backsolve(qr.R(PU_t), I_B))
    qr.qy(PU_t, t(qr.qty(QR, Y)))
    Rinv %*% (t(qr.Q(QR)) %*% Y %*% qr.Q(PU_t)) %*% Pinv
  },
  kronecker = {
     fit <- lm.fit(kronecker(t(B), A), as.vector(Y))
     tmp <- matrix(fit$coefficients, nrow = ncol(A), ncol = nrow(B))
     matrix(tmp, nrow = ncol(A), ncol = nrow(B))
  }
)
```


```{r}
solve_y_axb <- function(Y, A = NULL, B = NULL){
  stopifnot(is.matrix(Y))
  stopifnot(is.null(A) || is.matrix(A))
  stopifnot(is.null(B) || is.matrix(B))
  
  if(! is.null(A) && ! is.null(B)){
    stopifnot(nrow(Y) == nrow(A))
    stopifnot(ncol(Y) == ncol(B))
    # fit <- lm.fit(kronecker(t(B), A), as.vector(Y))
    tmp <- solve(t(A) %*% A) %*% t(A) %*% Y %*% t(B) %*% solve(B %*% t(B))
  }else if(is.null(B)){
    fit <- lm.fit(A, Y)
    tmp <- matrix(fit$coefficients, nrow = ncol(A), ncol = ncol(Y))
  }else if(is.null(A)){
    fit <- lm.fit(t(B), t(Y))
    tmp <- t(matrix(fit$coefficients, nrow = nrow(B), ncol = nrow(Y)))
  }else{
    stop("Either A or B must be non-null")
  }
  tmp[is.na(tmp)] <- 0
  tmp
}

solve_y_axb(Y, A, B)
X_true

solve_y_axb(Y, A = A)
X_true %*% B

solve_y_axb(Y, B = B)
A %*% X_true
```



```{r}
QR <- qr(A)
R <- qr.R(QR)

PU_t <- qr(t(B))
P <- t(qr.R(PU_t))

R[10,,drop=FALSE] %*% X %*% P[,1,drop=FALSE]

```

