---
title: "R Notebook"
---


```{r}
library(tidyverse)
library(glue)
source("util.R")
```



```{r}
pert_res <- bind_rows(readRDS("../benchmark/output/double_perturbation_results_predictions.RDS"))
parameters <- readRDS(file.path("../benchmark/output/double_perturbation_results_parameters.RDS")) %>%
  map(\(p) tibble(id = p$id, name = p$name, parameters = as_tibble(p$parameters), 
                  train = names(p$test_train_labels), perturbation = p$test_train_labels)) %>%
  bind_rows() %>%
  unnest(perturbation) %>%
  unpack(parameters)
```



```{r, paged.print=FALSE}
res <- pert_res %>%
  mutate(perturbation_split = str_split(perturbation, pattern = "[+_]", n = 2)) %>%
  mutate(perturbation_split = map(perturbation_split, \(x) {
    if(all(x == "ctrl" | x == "")) "ctrl" 
    else if(length(x) == 2) x
    else c(x, "ctrl")
  })) %>%
  mutate(perturbation = map_chr(perturbation_split, paste0, collapse = "+")) %>%
  tidylog::left_join(parameters, by = c("id", "name", "perturbation")) %>%  # Matches most of x. Non matches are from scGPT and are not in training
  tidylog::filter(! is.na(train)) %>%
  separate(name, sep = "-", into = c("dataset_name2", "seed2", "method"), convert = TRUE) %>%
  tidylog::filter(dataset_name2 == dataset_name | seed2 == seed) %>%
  dplyr::select(-c(dataset_name2, seed2))

res
```


```{r, paged.print=FALSE}
res %>%
  filter(method == "ground_truth" & seed == 1) %>%
  mutate(n_pert = lengths(map(perturbation_split, \(x) setdiff(x, "ctrl")))) %>%
  dplyr::count(dataset_name, n_pert) 
  
```


```{r, paged.print=FALSE}
long2matrix <- function(x, rows, cols, values, ...){
  df_mat <- x |>
    transmute({{rows}}, {{cols}}, {{values}}) |>
    pivot_wider(id_cols = {{rows}}, names_from = {{cols}}, values_from = {{values}}, ...) 
  mat<- as.matrix(df_mat[,-1])
  rownames(mat) <- df_mat[[1]]
  mat
}

res |>
  filter(seed == 1) |>
  mutate(present = map_lgl(prediction, \(x) ! is.na(x[1]))) |>
  (\(data){
    mat <- long2matrix(data, rows = method, cols = perturbation, values = present, values_fn = \(x) x * 1.0) 
    mat[is.na(mat)] <- 0
    ComplexHeatmap::pheatmap(mat, main = "Valid perturbations", breaks = c(0,1), color = c("lightgrey", "darkred"),
                             show_row_dend = FALSE, show_column_dend = FALSE, show_colnames = FALSE, legend = FALSE)
  })()

```



```{r, paged.print=FALSE}
baselines <- res %>%
  filter(method == "ground_truth" & perturbation == "ctrl") %>%
  dplyr::select(baseline = prediction, dataset_name, seed)
```

```{r, paged.print=FALSE}
res <- bind_rows(res, res %>%
  distinct(perturbation, perturbation_split, dataset_name, test_train_config_id, seed, train) %>%
  inner_join(baselines %>% dplyr::rename(prediction = baseline), by = c("dataset_name", "seed")) %>%
  mutate(method = "no_change"))
```



```{r, paged.print=FALSE}
expr_rank_df <- res %>%
  filter(method == "ground_truth" & perturbation == "ctrl") %>%
  dplyr::select(dataset_name, seed, observed = prediction) %>%
  mutate(gene_name = map(observed, names)) %>%
  unnest(c(gene_name, observed)) %>%
  mutate(expr_rank = rank(desc(observed), ties = "first"), .by = c(seed, dataset_name)) %>%
  dplyr::select(dataset_name, seed, gene_name, expr_rank)

expr_var_rank_df <- res %>%
  filter(method == "ground_truth") %>% 
  dplyr::select(dataset_name, seed, perturbation, observed = prediction) %>%
  mutate(gene_name = map(observed, names)) %>%
  unnest(c(gene_name, observed)) %>%
  summarize(var = var(observed), .by = c(dataset_name, seed, gene_name)) %>%
  mutate(var_rank = rank(desc(var), ties = "first"), .by = c(seed, dataset_name)) %>%
  dplyr::select(dataset_name, seed, gene_name, var_rank)
  
de_rank_df <- res %>%
  filter(method == "ground_truth") %>% 
  dplyr::select(dataset_name, seed, perturbation, observed = prediction) %>%
  mutate(gene_name = map(observed, names)) %>%
  unnest(c(gene_name, observed)) %>%
  left_join(baselines |> mutate(gene_name = map(baseline, names)) |> unnest(c(gene_name, baseline)), by = c("dataset_name", "seed", "gene_name")) %>%
  mutate(de = abs(observed - baseline)) %>%
  mutate(de_rank = rank(desc(de), ties = "first"), .by = c(seed, dataset_name, perturbation)) %>%
  dplyr::select(dataset_name, seed, perturbation, gene_name, de_rank)
```


```{r}
mem.maxVSize(vsize = Inf)
```


```{r, paged.print=FALSE}
contr_res <- tidylog::full_join(filter(res, method != "ground_truth"),
                                filter(res, method == "ground_truth") %>% dplyr::select(dataset_name, seed, perturbation, observed = prediction),
           by = c("dataset_name", "seed", "perturbation"))

res_metrics <- contr_res %>%
  tidylog::left_join(baselines, by = c("dataset_name", "seed")) %>%
  dplyr::select(-c(id, test_train_config_id)) %>%
  mutate(gene_name = map(prediction, names)) %>%
  unnest(c(gene_name, prediction, observed, baseline)) %>%
  inner_join(expr_rank_df %>% dplyr::select(dataset_name, seed, gene_name, expr_rank) %>% filter(expr_rank <= 1000), by = c("dataset_name", "seed", "gene_name")) %>%
  summarize(r2 = cor(prediction, observed),
         r2_delta = cor(prediction - baseline, observed - baseline),
         l2 =sqrt(sum((prediction - observed)^2)),
         .by = c(dataset_name, seed, method, perturbation, train))

res_metrics
```




```{r, paged.print=FALSE}
method_labels <- c("gears" = "GEARS", "scgpt" = "scGPT", "scfoundation" = "scFoundation", "additive_model" = "Additive", "lpm" = "LPM", "no_change" = "No Change")
dataset_labels <- c("norman_from_scfoundation" = "Norman")

main_pl_data <- res_metrics %>%
  filter(train %in% c("test", "val")) %>%
  mutate(method = factor(method, levels = names(method_labels))) %>%
  mutate(dataset_name = factor(dataset_name, levels = names(dataset_labels))) 

main_pl_double_pearson <- main_pl_data %>%
  ggplot(aes(x = method, y = r2_delta)) +
    geom_hline(yintercept = 0, color = "black", linewidth = 0.2) +
    ggbeeswarm::geom_quasirandom(size = 0.1, color =  "#444444", alpha = 0.6) +
    stat_summary(geom = "crossbar", fun = mean, color = "red") +
    facet_wrap(vars(dataset_name), scales = "free_x", labeller = as_labeller(dataset_labels), nrow = 1) +
    scale_x_discrete(labels = method_labels) +
    scale_y_continuous(limits = c(-0.25, 1), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 90)) +
    labs(y = "Pearson delta") +
    theme(axis.title.x = element_blank(),
          panel.grid.major.y = element_line(color = "lightgrey", linewidth = 0.1),
          panel.grid.minor.y = element_line(color = "lightgrey", linewidth = 0.1),
          panel.spacing.x = unit(3, "mm"))

main_pl_double_l2 <- main_pl_data %>%
  mutate(highlight = (perturbation %in% c("CEBPE+KLF1", "TGFBR2+ETS2") & method == "additive_model")) %>%
  ggplot(aes(x = method, y = l2)) +
    geom_hline(yintercept = 0, color = "black", linewidth = 0.2) +
    ggbeeswarm::geom_quasirandom(aes(color = highlight), size = 0.1) +
    # ggbeeswarm::geom_quasirandom(size = 0.1, color =  "#444444", alpha = 0.6) +
    stat_summary(geom = "crossbar", fun = mean, color = "red") +
    facet_wrap(vars(dataset_name), scales = "free_x", labeller = as_labeller(dataset_labels), nrow = 1) +
    scale_x_discrete(labels = method_labels) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(add = c(0, 0.5))) +
    scale_color_manual(values = c("TRUE" = "black", "FALSE" = alpha("#444444", 0.6))) +
    guides(x = guide_axis(angle = 90), color = "none") +
    labs(y = "Prediction error ($L_2$)") +
    theme(axis.title.x = element_blank(),
          panel.grid.major.y = element_line(color = "lightgrey", linewidth = 0.1),
          panel.grid.minor.y = element_line(color = "lightgrey", linewidth = 0.1),
          panel.spacing.x = unit(3, "mm"))

main_pl_double_pearson
main_pl_double_l2
```


```{r, paged.print=FALSE}
sel_perts <- res_metrics %>%
  filter(method == "additive_model") %>%
  filter(train %in% c("test", "val")) %>%
  arrange(l2) %>%
  slice(c(3, n()-2))

obs_pred_corr_pl <- contr_res %>%
  inner_join(sel_perts, by = c("dataset_name", "seed", "method", "perturbation")) %>%
  mutate(perturbation = fct_reorder(perturbation, -l2)) %>%
  tidylog::left_join(baselines, by = c("dataset_name", "seed")) %>%
  dplyr::select(-c(id, test_train_config_id)) %>%
  mutate(gene_name = map(prediction, names)) %>%
  unnest(c(gene_name, prediction, observed, baseline)) %>%
  inner_join(expr_rank_df %>% dplyr::select(dataset_name, seed, gene_name, expr_rank) %>% filter(expr_rank <= 1000), by = c("dataset_name", "seed", "gene_name")) %>%
  ggplot(aes(x = observed, y = prediction)) +
    geom_text(data = . %>% summarize(l2 = first(l2), .by = perturbation), aes(label = paste0("error: ", round(l2, 1))),
              x = -Inf, y = Inf, hjust = -0.1, vjust = 1.2, size = font_size_tiny / .pt) +
    geom_abline(linewidth = 0.2, linetype = "dashed") +
    geom_point(size = 0.5, stroke = 0) +
    coord_fixed(xlim = c(0.1, 5.5), ylim = c(0.1, 5.5)) +
    scale_x_continuous(breaks = c(1, 3, 5)) +
    scale_y_continuous(breaks = c(1, 3, 5)) +
    facet_wrap(vars(perturbation), ncol = 1) +
    labs(x = "observed expression", y = "predicted expression\n(sum of single effects)")

obs_pred_corr_pl
```

```{r, paged.print=FALSE}
all_combs <- tibble(perturbation = res$perturbation |> discard(\(x) str_detect(x, "ctrl")) |> unique()) %>%
  mutate(split = str_split(perturbation, "\\+")) %>%
  mutate(combs = map(split, \(x) list(x, c(x[1], "ctrl"), c(x[2], "ctrl"), "ctrl")),
         labels = map(split, \(x) c("AB", "A", "B", "ctrl"))) %>%
  transmute(pert_group = perturbation, 
            combs = map(combs, \(x) map(x, sort, method = "radix")),
            labels) %>%
  unnest(c(combs, labels))

ground_truth_df <- res %>%
  filter(method == "ground_truth") %>%
  mutate(perturbation_split = map(perturbation_split, sort, method = "radix")) %>%
  dplyr::select(perturbation, perturbation_split, seed, train, ground_truth = prediction) %>%
  inner_join(all_combs, by = c("perturbation_split" = "combs"), relationship = "many-to-many") %>% 
  unnest_named_lists(ground_truth, names_to = "gene_name") %>%
  pivot_wider(id_cols = c(gene_name, pert_group, seed), names_from = labels, values_from = ground_truth) %>%
  mutate(error = `AB` - (A + B - ctrl)) %>%
  # mutate(error_clever = broom::augment(lm(`AB` - ctrl ~ I(A - ctrl) + I(B - ctrl) - 1))$.resid, .by = pert_group)
  mutate(error_clever = broom::augment(lm(`AB` - ctrl ~ I(A - ctrl + B - ctrl) - 1))$.resid, .by = pert_group)
```


```{r, paged.print=FALSE}
pl_data <- ground_truth_df %>%
  left_join(expr_rank_df %>% dplyr::select(gene_name, rank = expr_rank), by = c("gene_name")) %>% 
  mutate(sum_abs_changes = abs(A - ctrl) + abs(B - ctrl)) %>%
  mutate(abs_error = abs(error)) %>%
  mutate(abs_error = if_else(abs_error > 1, Inf, abs_error)) 


frac_nonlin_pl1 <- pl_data %>%
  summarize(frac_nonlinear = mean(abs(error) > 0.15), .by = pert_group) %>%
  ggplot(aes(x = frac_nonlinear)) +
    geom_histogram(bins = 20) +
    scale_x_continuous(labels = scales::label_percent(suffix = "\\%")) +
    scale_y_continuous(limits = c(-1e-3, NA), expand = expansion(mult = c(0, 0.1))) +
    labs(title = "(B) Fraction of genes with non-linear interaction effect per double perturbation",
         subtitle = "All genes ($19\\,264$)",
         x = "Percent of genes with $|\\textrm{true interaction}| > 0.15$",
         y = "Number of double perturbations") +
    theme(plot.title.position = "plot")

frac_nonlin_pl2 <- pl_data %>%
  filter(rank <= 1000) %>%
  summarize(frac_nonlinear = mean(abs(error) > 0.15), .by = pert_group) %>%
  ggplot(aes(x = frac_nonlinear)) +
    geom_histogram(bins = 20) +
    scale_x_continuous(labels = scales::label_percent(suffix = "\\%")) +
    scale_y_continuous(limits = c(-1e-3, NA), expand = expansion(mult = c(0, 0.1))) +
    labs(title = "",
         subtitle = "$1\\,000$ most highly expressed genes",
         x = "Percent of genes with $|\\textrm{true interaction}| > 0.15$",
         y = "Number of double perturbations")  +
    theme(plot.title.position = "plot")

nonlin_magnitude_comp_pl1 <- pl_data %>%
  ggplot(aes(x = sum_abs_changes, y = abs_error)) +
    ggrastr::rasterize(geom_point(aes(color = abs_error < 0.15), size = 0.1, stroke = 0), dpi = 600) +
    scale_x_log10(labels = scales::label_log(), limits = c(5e-5, NA))  +
    scale_y_continuous(limits = c(0, 1), expand = expansion(0)) +
    scale_color_manual(values = c("TRUE" = "black", "FALSE" = "red"), 
                                  labels = c("TRUE" = "$|\\textrm{true interaction}| \\le 0.15$",
                                             "FALSE" = "$|\\textrm{true interaction}| > 0.15$")) +
    coord_cartesian(clip = "off") +
    guides(color = guide_legend(override.aes = list(size = 2))) +
    labs(title = "(A) Size of true interaction effects vs.\ size of single effects",
          subtitle = "All genes ($19\\,264$)",
         x = "Sum of absolute expression changes in single perturbations", 
         y = "Absolute true interaction", color= "") +
    theme(legend.position = "inside", legend.position.inside = c(0.1, 0.8),
          plot.title.position = "plot") 

nonlin_magnitude_comp_pl2 <- pl_data %>%
  filter(rank <= 1000) %>%
  ggplot(aes(x = sum_abs_changes, y = abs_error)) +
    ggrastr::rasterize(geom_point(aes(color = abs_error < 0.15), size = 0.1, stroke = 0), dpi = 600) +
    scale_x_log10(labels = scales::label_log(), limits = c(5e-5, NA))  +
    scale_y_continuous(limits = c(0, 1), expand = expansion(0)) +
    scale_color_manual(values = c("TRUE" = "black", "FALSE" = "red"), 
                                  labels = c("TRUE" = "$|\\textrm{true interaction}| \\le 0.15$",
                                             "FALSE" = "$|\\textrm{true interaction}| > 0.15$")) +
    coord_cartesian(clip = "off") +
    guides(color = guide_legend(override.aes = list(size = 2))) +
    labs(title = "",
         subtitle = "$1\\,000$ most highly expressed genes",
         x = "Sum of absolute expression changes in single perturbations", 
         y = "Absolute true interaction", color= "") +
    theme(legend.position = "inside", legend.position.inside = c(0.1, 0.8),
          plot.title.position = "plot") 


scaled_add_model_pl1 <- pl_data %>%
  summarize(frac_nonlinear_clever = mean(abs(error_clever) > 0.15), 
            frac_nonlinear_orig = mean(abs(error) > 0.15), 
            .by = pert_group) %>%
  ggplot(aes(x = frac_nonlinear_orig, y = frac_nonlinear_clever)) +
    geom_point(size = 0.6) +
    geom_abline(color = "grey", linetype = "dashed") +
    scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1)), labels = scales::label_percent(suffix = "\\%")) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1)), labels = scales::label_percent(suffix = "\\%")) +
    labs(title = "(C) Additive model ($\\delta AB = \\delta A + \\delta B$) vs.\\ scaled additive model ($\\delta AB = \\alpha (\\delta A + \\delta B)$)",
         subtitle = "All genes ($19\\,264$)",
         x = "Percent of genes with $|\\textrm{true interaction}| > 0.15$\nwith additive model",
         y = "Percent of genes with\n$|\\textrm{true interaction}| > 0.15$\nwith scaled additive model") +
    coord_fixed() +
    theme(plot.title.position = "plot")

scaled_add_model_pl2 <- pl_data %>%
  filter(rank <= 1000) %>%
  summarize(frac_nonlinear_clever = mean(abs(error_clever) > 0.15), 
            frac_nonlinear_orig = mean(abs(error) > 0.15), 
            .by = pert_group) %>%
  ggplot(aes(x = frac_nonlinear_orig, y = frac_nonlinear_clever)) +
    geom_point(size = 0.6) +
    geom_abline(color = "grey", linetype = "dashed") +
    scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1)), labels = scales::label_percent(suffix = "\\%")) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1)), labels = scales::label_percent(suffix = "\\%")) +
    labs(title = "",
         subtitle = "$1\\,000$ most highly expressed genes",
         x = "Percent of genes with $|\\textrm{true interaction}| > 0.15$\nwith additive model",
         y = "Percent of genes with\n$|\\textrm{true interaction}| > 0.15$\nwith scaled additive model") +
    coord_fixed() +
    theme(plot.title.position = "plot")
      
frac_nonlin_pl1
frac_nonlin_pl2
nonlin_magnitude_comp_pl1 
nonlin_magnitude_comp_pl2
scaled_add_model_pl1
scaled_add_model_pl2
```


```{r}
plot_assemble(
  add_plot(nonlin_magnitude_comp_pl1, x = 0, y = 1, width = 70, height = 45),
  add_plot(nonlin_magnitude_comp_pl2, x = 75, y = 1, width = 70, height = 45),
  
  add_plot(frac_nonlin_pl1, x = 0, y = 49, width = 70, height = 47.5),
  add_plot(frac_nonlin_pl2, x = 75, y = 49, width = 70, height = 47.5),

  add_plot(scaled_add_model_pl1, x = 0, y = 100, width = 80, height = 45),
  add_plot(scaled_add_model_pl2, x = 75, y = 100, width = 80, height = 45),

  width = 170, height = 145, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/suppl-double_perturbation_effect_size.pdf"
)
```



```{r, paged.print=FALSE}
filter_gt_df <- ground_truth_df %>%
  inner_join(expr_rank_df %>% dplyr::select(gene_name, seed, rank = expr_rank) %>% filter(rank <= 1000) , by = c("gene_name", "seed")) 
  

probs <- c(0.3, 0.7)
xcoords <- qnorm(p = probs)
ycoords <- quantile(filter_gt_df$error, prob = probs)
sd_est <- unname(diff(ycoords) / diff(xcoords))
mean_est <- mean(ycoords)

# Doesn't work
# locfdr:::locmle(filter_gt_df$error, xlim = c(0, 1))

annotate_ticks <- function(origin = c(0,0), dir = c(1,0), at = seq(-10, 10), length = 0.1, ...){
  orth_dir <- c(dir[2], -dir[1])
  pos <- t(lemur:::mply_dbl(at, \(t) origin + t * dir, ncol=2))
  start <- pos + length/2 * orth_dir
  end <- pos - length/2 * orth_dir
  dat <- tibble(pos = t(pos), start = t(start), end = t(end))
  geom_segment(data = dat, aes(x = start[,1], xend = end[,1], y = start[,2], yend = end[,2]), ...)
}

annotate_labels_along <- function(origin = c(0,0), dir = c(1,0), labels = at, at = 0, offset = 0, extra_df = NULL, ...){
  orth_dir <- c(dir[2], -dir[1])
  pos <- t(lemur:::mply_dbl(at, \(t) origin + t * dir, ncol=2))
  dat <- bind_cols(tibble(pos = t(pos), labels), extra_df)
  angle <- atan2(dir[2], dir[1]) / pi * 180
  geom_text(data=dat, aes(label = labels, x = pos[,1] + offset * orth_dir[1], y = pos[,2] + offset * orth_dir[2]), angle = angle, ...)
}

label_pos <- c(0.001, 0.01, 0.1, 0.2, 0.5, 0.8, 0.9, 0.99, 0.999)

qq_pl <- filter_gt_df %>%
  mutate(percent_rank = percent_rank(error)) %>%
  arrange(error) %>%
  mutate(expect_quantile = qnorm(ppoints(n()))) %>%
  ggplot(aes(x = expect_quantile, y = error)) +
    geom_abline(slope = sd_est) +
    annotate_ticks(dir = c(1, sd_est), at  = qnorm(label_pos), length = 0.17) +
    annotate_labels_along(dir = c(1, sd_est), at = qnorm(label_pos[1:4]), labels = label_pos[1:4], offset = -0.25, size = font_size_small / .pt) +
    annotate_labels_along(dir = c(1, sd_est), at = qnorm(label_pos[5:9]), labels = label_pos[5:9], offset = 0.25, size = font_size_small / .pt) +
    annotate_labels_along(dir = c(1, sd_est), at = 4.5, labels = "Percentile", offset = 0.15, size = font_size_small / .pt) +
    ggrastr::rasterize(geom_point(size = 0.3, stroke = 0), dpi = 300) +
    coord_fixed() +
    labs(title = "Quantile-Quantile plot of the deviation from the additive model",
         x = "Quantiles of a standard normal distribution", y = "Quantiles of the\ntrue deviation from additive model")
qq_pl
```



```{r}
plot_assemble(
  add_text("(A)", x = 2.7, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(qq_pl, x = 3, y = 2, width = 120, height = 47.5),
  
  width = 170, height = 50, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/suppl-qqplot.pdf"
)
```


```{r, paged.print=FALSE}
bin_numeric <- function(label){
  mat <- str_match(label, "^[\\(\\[]([+-]?\\d+\\.?\\d*),\\s*([+-]?\\d+\\.?\\d*)[\\]\\)]$")[,2:3,drop=FALSE]
  array(as.numeric(mat), dim(mat))
}

slice_first <- function(data, condition, order_by = row_number(), ...){
  filtered_data <- filter(data, {{condition}})
  filtered_data <- arrange(filtered_data, {{order_by}})
  slice_head(filtered_data, ...)
}

dens_ratio_df <- filter_gt_df %>%
  filter(seed == 1) %>%
  mutate(obs_dens = error |> (\(err){
    dens <- density(err, bw = "nrd0")
    approx(dens$x, dens$y, err)$y
  })(),
  expected_dens = dnorm(error, mean = mean_est, sd = sd_est)) %>%
  mutate(ratio =  pmin(1, expected_dens / obs_dens)) 

upper_thres <- dens_ratio_df %>% slice_first(ratio < 0.1 & error > 0, order_by = error) %>% pull(error)
lower_thres <- dens_ratio_df %>% slice_first(ratio < 0.1 & error < 0, order_by = desc(error)) %>% pull(error)

error_histogram <- dens_ratio_df %>%
  mutate(error_bin = santoku::chop_width(error, width = 0.01)) %>%
  mutate(bin_num = bin_numeric(as.character(error_bin))) %>%
  summarize(count_h0 = n() * mean(ratio),
            count_h1 = n() * (1-mean(ratio)),
            .by = c(error_bin, bin_num)) %>%
  pivot_longer(starts_with("count_"), names_sep = "_", names_to = c(".value", "origin"))  %>%
  mutate(origin = factor(origin, levels = c("h1", "h0"))) %>%
  mutate(bin_width = matrixStats::rowDiffs(bin_num)) %>%
  ggplot(aes(x = rowMeans(bin_num), y = count / sum(count) / bin_width)) +
    geom_col(aes(fill = origin), width = 0.01, position = "stack", show.legend = FALSE) +
    geom_function(fun = \(x) dnorm(x, mean = mean_est, sd = sd_est), n = 1e4, color = "red") +
    geom_vline(xintercept = c(lower_thres, upper_thres), color = "#040404", linewidth = 0.2) +
    scale_fill_manual(values = c("h0" = "lightgrey", "h1" = "black")) +
    scale_x_continuous(limits = c(-0.45, 0.45)) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    labs(y = "density", x = "Deviation from additive model")

error_histogram
```


```{r}
locfdr::locfdr()
```



```{r}
pl_data %>%
  filter(rank <= 1000) %>%
  summarize(frac_nonlinear = mean(abs(error) > 0.15), .by = pert_group) %>%
  pull(frac_nonlinear) %>% summary()
```




```{r, paged.print=FALSE}
# For correlation, I could use the TTR::runCor function, but it is slow
strat_data_init <- contr_res %>%
  filter(train != "train") %>%
  tidylog::left_join(baselines, by = c("dataset_name", "seed")) %>%
  dplyr::select(-c(id, test_train_config_id, prediction_std, epochs)) %>%
  mutate(gene_name = map(prediction, names)) %>%
  unnest(c(gene_name, prediction, observed, baseline))

strat_data_expr_rank <- strat_data_init %>%
  left_join(expr_rank_df %>% dplyr::select(dataset_name, seed, gene_name, rank = expr_rank), by = c("dataset_name", "seed", "gene_name")) %>%
  arrange(rank) %>%
  mutate(dist = sqrt(cumsum((prediction - observed)^2)),
         .by = c(dataset_name, seed, method, perturbation))

strat_data_expr_var_rank <- strat_data_init %>%
  left_join(expr_var_rank_df %>% dplyr::select(dataset_name, seed, gene_name, rank = var_rank), by = c("dataset_name", "seed", "gene_name")) %>%
  arrange(rank) %>%
  mutate(dist = sqrt(cumsum((prediction - observed)^2)),
         .by = c(dataset_name, seed, method, perturbation))

strat_data_de_rank <- strat_data_init %>%
  left_join(de_rank_df %>% dplyr::select(dataset_name, seed, perturbation, gene_name, rank = de_rank), by = c("dataset_name", "seed", "gene_name", "perturbation")) %>%
  arrange(rank) %>%
  mutate(dist = sqrt(cumsum((prediction - observed)^2)),
         .by = c(dataset_name, seed, method, perturbation))
```


```{r,paged.print=FALSE}
bind_rows(
  strat_data_expr_rank %>% mutate(sorted_by = "expr"),
  strat_data_expr_var_rank %>% mutate(sorted_by = "expr_var"),
  strat_data_de_rank %>% mutate(sorted_by = "de")
) %>%
  mutate(sorted_by = factor(sorted_by, levels = c("expr", "expr_var", "de"))) %>%
  summarize(dist_mean = mean(dist),
            dist_se = sd(dist) / sqrt(first(rank)),
            .by = c(method, dataset_name, seed, rank, sorted_by)) %>%
  ggplot(aes(x = rank, y = dist_mean)) +
    geom_ribbon(aes(ymin = dist_mean - 1.96 * dist_se, ymax = dist_mean + 1.96 * dist_se, group = method), alpha = 0.2) +
    geom_line(aes(color = method)) +
    geom_vline(data = tibble(rank = 1000, sorted_by = factor("expr", levels = c("expr", "expr_var", "de"))), aes(xintercept = rank)) +
    scale_x_log10() +
    facet_wrap(vars(sorted_by), labeller = as_labeller(c("expr" = "sorted by expression", "expr_var" = "sorted by variance",
                                             "de" = "sorted by differential expression")))
```

```{r,paged.print=FALSE}
strat_merged <- bind_rows(
  strat_data_expr_rank %>% mutate(sorted_by = "expr"),
  strat_data_de_rank %>% mutate(sorted_by = "de")
) %>%
  mutate(sorted_by = factor(sorted_by, levels = c("expr", "expr_var", "de"))) %>%
  summarize(dist_mean = mean(dist),
            dist_se = sd(dist) / sqrt(first(rank)),
            .by = c(method, dataset_name, seed, rank, sorted_by)) 

strat_pl <- strat_merged %>%
  ggplot(aes(x = rank, y = dist_mean)) +
    ggrastr::rasterize(geom_line(aes(color = method), show.legend=FALSE), dpi = 600) +
    geom_text(data = . %>% filter(rank == max(rank)), aes(label = method_labels[method]), hjust = 0.5, vjust = -0.2, size = font_size_small / .pt) +
    geom_vline(data = tibble(rank = 1000, sorted_by = factor("expr", levels = c("expr", "expr_var", "de"))), aes(xintercept = rank),
               linewidth = 0.4, linetype = "dashed", color = "grey") +
    scale_x_log10(labels = scales::label_comma()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
    facet_wrap(vars(sorted_by), labeller = as_labeller(c("expr" = "genes sorted by expression",
                                                          "de" = "genes sorted by differential expression"))) +
    labs(x = "top $n$ genes (log-scale)", y = "Prediction error ($L_2$)") +
    coord_cartesian(clip = "off") +
    theme(panel.spacing.x = unit(4, "mm"))

strat_pl
```


```{r, paged.print=FALSE}

inter_pred_dat <- res %>%
  # filter(seed == 1) %>%
  filter(train %in% c("test", "val")) %>%
  filter(lengths(map(perturbation_split, \(x) setdiff(x, "ctrl"))) == 2) %>%
  tidylog::left_join(baselines, by = c("dataset_name", "seed")) %>%
  dplyr::select(perturbation, method, seed, prediction, baseline) %>%
  mutate(gene_name = map(prediction, names)) %>%
  unnest(c(gene_name, prediction, baseline)) %>%
  inner_join(expr_rank_df %>% dplyr::select(gene_name, seed, expr_rank) %>% filter(expr_rank <= 1000), by = c("gene_name", "seed")) %>%
  pivot_wider(id_cols = c(perturbation, gene_name, baseline, seed), names_from = method, values_from = prediction) %>%
  pivot_longer(c(scgpt, gears, scfoundation, lpm, no_change), names_to = "method") 
```

```{r}
nonlin_fun <- function(p1, p2, vec1 = NULL, vec2 = NULL, extrapolate_factor = 0, n_interpolations = 101,
                       return = c("function", "mapping")){
  return <- match.arg(return)
  t <- seq(0, 1, length.out = n_interpolations)
  if(is.null(vec1) && is.null(vec2)){
    bezier_coefs <- rbind((1-t), t)
    points <- cbind(p1, p2)
    vec1 <- p2 - p1
    vec2 <- p2 - p1
  }else if(is.null(vec1) && ! is.null(vec2)){
    bezier_coefs <- rbind((1-t)^2, 2 * (t - t^2), t^2)
    points <- cbind(p1, p2-vec2, p2)
    vec1 <- p2 - vec2 - p1
  }else if(!is.null(vec1) && is.null(vec2)){
    bezier_coefs <- rbind((1-t)^2, 2 * (t - t^2), t^2)
    points <- cbind(p1, p1+vec1, p2)
    vec2 <- p2 - (p1 + vec1)
  }else{
    bezier_coefs <- rbind((1-t)^3, 3 * t * (1 - t)^2, 3 * t^2 * (1-t), t^3)
    points <- cbind(p1, p1 + vec1, p2 - vec2, p2)
  }
  pred <- points %*% bezier_coefs
  extrapolate_factor <- rep_len(extrapolate_factor, 2)
  if(extrapolate_factor[1] > 0){
    pred <- cbind(p1 - extrapolate_factor[1] * vec1, pred)
  }
  if(extrapolate_factor[2] > 0){
    pred <- cbind(pred, p2 + extrapolate_factor[2] * vec2)
  }
  
  lookup_fun <- approxfun(x = pred[1,], y = pred[2,], rule = 1)
  function(v, return = c("function", "mapping")){
    return <- match.arg(return)
    if(return == "function"){
      lookup_fun(v)
    }else{
      pred
    }
  }
}

p1 <- c(0, -1)
p2 <- c(1,  0)
vec1 <- c(0, 0.5)
vec2 <- c(1, 0)

xg <- seq(-3, 3, l = 100)
fun <- nonlin_fun(p1 = p1, p2 = p2, vec1 = vec1, vec2 = vec2, extrapolate_factor = c(0, 10), n_interpolations = 30)
points <- fun(return = "mapping")[,-31]

tibble(x = points[1,], y = points[2,]) %>%
  ggplot(aes(x = x, y = y)) +
    geom_function(fun = fun, color = "pink", xlim = c(0, 1.5)) +
    geom_point() +
    annotate("point", x = p1[1], y = p1[2], color = "red") +
    annotate("point", x = p2[1], y = p2[2], color = "green") 
 
```

```{r, paged.print=FALSE}
lower_thres_fun1 <- nonlin_fun(p1 = c(-threshold, -0.6), p2 = c(0, -threshold), vec1 = c(0.01, 0.1), vec2 = 0.2 * c(1,1), extrapolate_factor = c(2, 0))
lower_thres_fun2 <- nonlin_fun(p1 = c(0.6, threshold), p2 = c(0, -threshold), vec1 = -c(0.1, 0.01), vec2 = -0.2 * c(1,1), extrapolate_factor = c(2, 0))
upper_thres_fun1 <- nonlin_fun(p1 = c(threshold, 0.6), p2 = c(0, threshold), vec1 = -c(0.01, 0.1), vec2 = -0.2 * c(1,1), extrapolate_factor = c(2, 0))
upper_thres_fun2 <- nonlin_fun(p1 = c(-0.6,-threshold), p2 = c(0, threshold), vec1 =  c(0.1, 0.01), vec2 = 0.2 * c(1,1), extrapolate_factor = c(2, 0))
`%|%` <- rlang::`%|%`


label_interaction_pred <- inter_pred_dat %>%
  mutate(obs_minus_add = ground_truth - additive_model,
         pred_minus_add = value - additive_model) %>%
  # mutate(pred_too_low = pred_minus_add < (lower_thres_fun1(obs_minus_add) %|% lower_thres_fun2(obs_minus_add) %|% -Inf),
  #        pred_too_high = pred_minus_add > (upper_thres_fun1(obs_minus_add) %|% upper_thres_fun2(obs_minus_add) %|% Inf)) %>%
  # mutate(prediction_label = case_when(
  #   pred_too_low ~ "Prediction too low",
  #   pred_too_high ~ "Prediction too high",
  #   obs_minus_add + pred_minus_add < -2 * threshold ~ "Good suppression prediction",
  #   obs_minus_add + pred_minus_add >  2 * threshold ~ "Good synergy prediction",
  #   TRUE ~ "Good additive prediction"
  # )) %>%
  # mutate(prediction_label = factor(prediction_label, c("Good synergy prediction", "Prediction too high", "Good suppression prediction", 
  #                                                      "Prediction too low", "Good additive prediction"))) %>%
  mutate(method = factor(method, levels = names(method_labels)))
  
pos_counts <- label_interaction_pred %>%
  dplyr::count(method, prediction_label) %>%
  mutate(n_label = scales::label_comma()(n)) %>%
  rowwise() %>%
  mutate(pos = matrix(case_when(
    prediction_label == "Prediction too high" ~ threshold * c(-1.5,1.5),
    prediction_label == "Prediction too low" ~ threshold * c(1.5,-1.5),
    prediction_label == "Good suppression prediction" ~ threshold * c(-1.5,-1.5),
    prediction_label == "Good synergy prediction" ~ threshold * c(1.5,1.5),
    prediction_label == "Good additive prediction" ~ c(0,0)
  ), nrow = 1))

base_colors <- c("lightgrey", "#00BA38", "#619CFF")
color_scale <- c("Good additive prediction" = base_colors[1], 
                 "Prediction too high" = colorspace::desaturate(base_colors[2], 0.7),
                 "Prediction too low"    = colorspace::desaturate(base_colors[3], 0.7),
                 "Good synergy prediction" = base_colors[2], 
                 "Good suppression prediction" = base_colors[3])


pert_pred_comparison <- label_interaction_pred %>%  
  ggplot(aes(x = obs_minus_add, y = pred_minus_add)) +
    ggrastr::rasterize(geom_point(aes(color = prediction_label), size = 0.3, stroke = 0), dpi = 600) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", alpha = 0.3) +
    shadowtext::geom_shadowtext(data = pos_counts, aes(x = pos[,1], y = pos[,2], label = n_label),
                                hjust = 0.5, vjust = 0.5, size = font_size_tiny / .pt, color = "black", bg.color = "white") +
    geom_hline(yintercept = c(lower_thres, upper_thres), linewidth = 0.2) +
    geom_vline(xintercept = c(lower_thres, upper_thres), linewidth = 0.2) +
    annotate("path", x = lower_thres_fun1(return="mapping")[1,], y = lower_thres_fun1(return="mapping")[2,], linewidth = 0.2) +
    annotate("path", x = lower_thres_fun2(return="mapping")[1,], y = lower_thres_fun2(return="mapping")[2,], linewidth = 0.2) +
    annotate("path", x = upper_thres_fun1(return="mapping")[1,], y = upper_thres_fun1(return="mapping")[2,], linewidth = 0.2) +
    annotate("path", x = upper_thres_fun2(return="mapping")[1,], y = upper_thres_fun2(return="mapping")[2,], linewidth = 0.2) +
    facet_wrap(vars(method), labeller = as_labeller(method_labels)) +
    scale_x_continuous(expand = expansion(add = 0)) +
    scale_y_continuous(expand = expansion(add = 0)) +
    scale_color_manual(values = color_scale) +
    coord_fixed(xlim = c(-0.6, 0.6), ylim = c(-0.6, 0.6)) +
    guides(color = guide_legend(override.aes = list(size = 2), ncol = 1)) +
    labs(x = "True deviation from additive model ($\\textrm{observed value} - \\textrm{sum of single effects}$)", 
         y = "Predicted deviation from additive model\n$\\textrm{predicted value} - \\textrm{sum of single effects}$", 
         color = "") +
    theme(panel.spacing.x = unit(4, "mm"))

pert_pred_comparison
```




```{r}
lower_curve_df <- tribble(
           ~x,          ~y,    ~angle,   ~handle_length,
  lower_thres,        -0.6,       90,               0.1,
            0, lower_thres,       45,               0.1,
  upper_thres,           0,       45,               0.1,
          0.6, upper_thres,        0,               0.1,
)

label_interaction_pred %>%  
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres & pred_minus_add > upper_thres ~ "Good synergy prediction",
    obs_minus_add < lower_thres & pred_minus_add < lower_thres ~ "Good suppression prediction",
    obs_minus_add > lower_thres & obs_minus_add < upper_thres & 
      pred_minus_add > lower_thres & pred_minus_add < upper_thres ~ "Good additive prediction",
    TRUE ~ "bad prediction"
  )) %>%
  ggplot(aes(x = obs_minus_add, y = pred_minus_add)) +
    ggrastr::rasterize(geom_point(aes(color = prediction_label), size = 0.1, stroke = 0), dpi = 600) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", alpha = 0.3) +
    geom_hline(yintercept = c(lower_thres, upper_thres), linewidth = 0.2) +
    geom_vline(xintercept = c(lower_thres, upper_thres), linewidth = 0.2) +
    # ggbezier::geom_bezier(data = lower_curve_df, aes(x = x, y = y, angle = angle, handle_length = handle_length), color = "darkgrey") +
    # ggbezier::geom_bezier(data = lower_curve_df %>% mutate(z = x, x = y, y = z, angle = rev(angle)), 
    #                       aes(x = x, y = y, angle = angle, handle_length = handle_length), color = "darkgrey") +
    facet_wrap(vars(method), labeller = as_labeller(method_labels)) +
    scale_x_continuous(expand = expansion(add = 0)) +
    scale_y_continuous(expand = expansion(add = 0)) +
    # scale_color_manual(values = color_scale) +
    coord_fixed(xlim = c(-0.6, 0.6), ylim = c(-1.2, 1.2)) +
    guides(color = guide_legend(override.aes = list(size = 2), ncol = 1)) +
    labs(x = "True deviation from additive model ($\\textrm{observed value} - \\textrm{sum of single effects}$)", 
         y = "Predicted deviation from additive model\n$\\textrm{predicted value} - \\textrm{sum of single effects}$", 
         color = "") +
    theme(panel.spacing.x = unit(4, "mm"))
```

```{r, paged.print=FALSE}
label_interaction_pred %>%
  summarize(cor = cor(obs_minus_add, pred_minus_add), .by = method)

clamp <- function(x, max, min = -max){
  case_when(
    x > max ~ max,
    x < min ~ min,
    .default = x
  )
}

label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  mutate(pred_minus_add = clamp(pred_minus_add, max = 0.8)) %>%
  ggplot(aes(x = pred_minus_add, fill = prediction_label)) +
    geom_histogram(bins = 100) +
    scale_x_continuous(limits = c(-0.8, 0.8)) +
    facet_wrap(vars(method))

pred_label_qual_df <- label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  mutate(pred_minus_add = clamp(pred_minus_add, max = 0.8)) %>%
  mutate(pred_minus_add_bin = santoku::chop_equally(pred_minus_add, groups = 200), .by = c(method)) %>%
  mutate(bin_num = bin_numeric(as.character(pred_minus_add_bin))) %>%
  count(bin_num, pred_minus_add_bin, prediction_label, method) %>%
  mutate(frac = n / sum(n), .by = c(bin_num, pred_minus_add_bin, method)) 


pred_label_qual_df %>%
  mutate(lower = cumsum(lag(n, default = 0)),
         upper = cumsum(n), 
         .by = c(method, bin_num, pred_minus_add_bin)) %>%
  mutate(bin_num = (bin_num - rowMeans(bin_num)) * 0.95 + rowMeans(bin_num)) %>%
  ggplot(aes(xmin = bin_num[,1], xmax = bin_num[,2], ymin = lower, ymax = upper)) +
    geom_rect(aes(fill = prediction_label), show.legend = FALSE) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    # labs(y = "density", x = "Deviation from additive model") +
    facet_wrap(vars(method), labeller = as_labeller(method_labels))

pred_label_qual_df %>%
  mutate(lower = cumsum(lag(n, default = 0)),
         upper = cumsum(n), 
         .by = c(method, bin_num, pred_minus_add_bin)) %>%
  mutate(bin_num = (bin_num - rowMeans(bin_num)) * 0.95 + rowMeans(bin_num)) %>%
  ggplot(aes(xmin = bin_num[,1], xmax = bin_num[,2], ymin = lower, ymax = upper)) +
    geom_rect(aes(fill = prediction_label), show.legend = FALSE) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    facet_wrap(vars(method), labeller = as_labeller(method_labels))

pred_label_qual_df %>%
  mutate(lower = cumsum(lag(n, default = 0)),
         upper = cumsum(n), 
         .by = c(method, bin_num, pred_minus_add_bin)) %>%
  mutate(bin_mean = rowMeans(bin_num)) %>%
  ggplot(aes(xmin = bin_mean-0.01, xmax = bin_mean + 0.01, ymin = lower, ymax = upper)) +
    geom_rect(aes(fill = prediction_label), show.legend = FALSE) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    facet_wrap(vars(method), labeller = as_labeller(method_labels))

pred_label_qual_df %>%
  filter(prediction_label == "True synergy") %>%
  ggplot(aes(x = bin_num[,1], y = frac)) +
    geom_step(aes(color = method), direction = "mid")

```


```{r, paged.print=FALSE}
label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  filter(pred_minus_add > 0.5) %>%
  filter(method == "scgpt") %>%
  mutate(prediction_label = factor(prediction_label, levels = c("True synergy", "True suppression", "True additive"))) %>%
  arrange(prediction_label, perturbation, desc(obs_minus_add)) %>%
  print(n = 200)


label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  filter(pred_minus_add > 0.5) %>%
  filter(method == "scgpt") %>%
  mutate(n_perts = length(unique(perturbation))) %>%
  summarize(n = n(), .by = c(gene_name, prediction_label, n_perts)) %>%
  filter(prediction_label == "True synergy") %>%
  arrange(desc(n))
```

```{r, paged.print=FALSE}
label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  filter(method == "scgpt" & seed == 3) %>%
  arrange(desc(pred_minus_add)) %>%
  mutate(tp = cumsum(obs_minus_add > upper_thres),
         fp = cumsum(obs_minus_add < upper_thres)) %>%
  mutate(fdp = fp / pmax(1, fp + tp)) %>%
  slice_max(pred_minus_add, n = 100, by = c(method, seed)) %>%
  print(n = 100)
```


```{r, paged.print=FALSE}
approx2 <- function(x, y, ...){
  data <- tibble({{x}}, {{y}})
  tmp <- as_tibble(approx(data[[1]], data[[2]], ...))
  colnames(tmp) <- colnames(data)
  tmp
}

label_interaction_pred %>%
  mutate(prediction_label = case_when(
    obs_minus_add > upper_thres ~ "True synergy",
    obs_minus_add < lower_thres ~ "True suppression",
    TRUE ~ "True additive"
  )) %>%
  group_by(method, seed) %>%
  arrange(desc(pred_minus_add)) %>%
  mutate(tp = cumsum(obs_minus_add > upper_thres),
         fp = cumsum(obs_minus_add < upper_thres)) %>%
  mutate(fdp = fp / pmax(1, fp + tp)) %>%
  arrange(fdp) %>%
  mutate(tp = cummax(tp)) %>%
  # mutate(tpr = tp / sum(obs_minus_add > upper_thres)) %>%
  # reframe(tmp = approx2(fdp, tpr, xout = seq(0, 1, length.out = 101), yleft = 0, yright = 1)) %>%
  # ungroup() %>%
  # unnest(tmp) %>%
  # summarize(tpr = median(tpr), .by = c(method, fdp)) %>%
  # print(n = 300)
  filter(seed == 1) %>%
  ggplot(aes(x = fdp, y = tp)) +
    # geom_line(aes(color = method, group = paste0(method, "-", seed))) +
    geom_step(aes(color = method), direction = "hv") +
    # scale_y_log10() +
    NULL
```


```{r}
plot_assemble(
  add_text("(A) Double perturbation prediction error", x = 2.7, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(main_pl_double_l2, x = 0, y = 4, width = 40, height = 47.5),
  add_plot(obs_pred_corr_pl, x = 40, y = 4, width = 30, height = 47.5),
  add_graphic("../illustrations/two_arrows.pdf", x = -1, y = -1.5, units = "mm"),

  add_text("(B) Prediction error depending on number of considered genes", x = 75, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(strat_pl, x = 75, y = 4, width = 90, height = 47.5),
  
  add_plot(error_histogram, x = 0, y = 60, width = 35, height = 40),
  
  add_text("(C) Prediction of non-additive perturbation effects", x = 2.7, y = 54, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(pert_pred_comparison + guides(color = "none"), x = 35, y = 54, width = 135, height = 60),
  # add_plot(my_get_legend(pert_pred_comparison), x = 135, y = 60, width = 40, height = 40),


  width = 170, height = 112, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/perturbation_prediction.pdf"
)
```




# Resource usage

```{r, paged.print=FALSE}
resource_df <- read_tsv("../benchmark/output/single_perturbation_jobs_stats.tsv")

norman_df <- resource_df %>%
  separate(name, into = c("dataset", "seed", "method"), sep = "-") %>%
  filter(dataset == "norman_from_scfoundation")

mem_pl <- norman_df %>%
  filter(metric == "max_mem_kbytes") %>%
  filter(method != "ground_truth") %>%
  mutate(method = factor(method, levels = names(method_labels))) %>%
  ggplot(aes(x = method, y = value * 1000)) +
    geom_point() +
    scale_y_continuous(labels = scales::label_bytes()) +
    scale_x_discrete(labels = method_labels) +
    labs(y = "Peak memory usage", x = "") +
    theme(panel.grid.major.y = element_line(color = "lightgrey", linewidth = 0.2))

dur_pl <- norman_df %>%
  filter(metric == "elapsed") %>%
  filter(method != "ground_truth") %>%
  mutate(method = factor(method, levels = names(method_labels))) %>%
  ggplot(aes(x = method, y = value)) +
    geom_point() +
    scale_y_log10(limits = c(60, NA), breaks = c(60, 10 * 60, 60 * 60, 6 * 60 * 60, 60 * 60 * 24, 3 * 60 * 60 * 24), 
                  labels = c("1 min", "10 min", "1 hour", "6 hours", "1 day", "3 days")) +
    scale_x_discrete(labels = method_labels) +
    labs(y = "Duration", x = "") +
    theme(panel.grid.major.y = element_line(color = "lightgrey", linewidth = 0.2))
```



```{r}
plot_assemble(
  add_text("(A)", x = 2.7, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(dur_pl, x = 3, y = 2, width = 60, height = 47.5),
  add_text("(B)", x = 70, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(mem_pl, x = 68, y = 2, width = 60, height = 47.5),
  
  width = 170, height = 50, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/suppl-resource_usage.pdf"
)
```



