---
title: "R Notebook"
---

```{r}
library(tidyverse)
```

```{r, paged.print=FALSE}
pert_res <- bind_rows(readRDS(file.path("../benchmark/output/perturbation_results_predictions.RDS")))
parameters <- readRDS(file.path("../benchmark/output/perturbation_results_parameters.RDS")) %>%
  map(\(p) tibble(id = p$id, name = p$name, parameters = as_tibble(p$parameters), 
                  train = names(p$test_train_labels), perturbation = p$test_train_labels)) %>%
  bind_rows() %>%
  unnest(perturbation) %>%
  unpack(parameters)
```


```{r, paged.print=FALSE}
res <- pert_res %>%
  mutate(perturbation_split = str_split(perturbation, pattern = "[+_]", n = 2)) %>%
  mutate(perturbation_split = map(perturbation_split, \(x) {
    if(all(x == "ctrl" | x == "")) "ctrl" 
    else if(length(x) == 2) x
    else c(x, "ctrl")
  })) %>%
  mutate(perturbation = map_chr(perturbation_split, paste0, collapse = "+")) %>%
  tidylog::left_join(parameters, by = c("id", "name", "perturbation")) %>%
  separate(name, into = c("dataset2", "seed2", "method"), sep = "-") %>%
  mutate(single_pert = map_lgl(perturbation_split, \(x) "ctrl" %in% x)) %>%
  dplyr::select(-c(id, test_train_config_id, dataset2, seed2), dataset = dataset_name) %>%
  filter(method %in% c("additive_model", "ground_truth"))

res
```


```{r, paged.print=FALSE}
prep_data <- res %>%
  mutate(gene_name = map(prediction, names)) %>%
  unnest(c(prediction, gene_name)) %>%
  pivot_wider(id_cols = c(perturbation, gene_name, perturbation_split, train, single_pert), names_from = method, values_from = prediction) %>%
  mutate(diff = ground_truth - additive_model) %>%
  mutate(diff2 = broom::augment(lm(ground_truth ~ additive_model - 1))$.resid, .by = perturbation) 
```


```{r, paged.print=FALSE}
n_nonadd_gene_df <- prep_data %>%
  mutate(category = case_when(
    diff < -0.15 ~ "suppressive",
    diff >  0.15 ~ "synergistic",
    TRUE ~ "additive"
  )) %>%
  filter(! single_pert) %>%
  count(perturbation, category) %>%
  pivot_wider(id_cols = perturbation, names_from = category, values_from = n, values_fill = 0) 

n_nonadd_gene_df %>%
  ggplot(aes(x = suppressive, y = synergistic)) +
    geom_point() +
    geom_abline() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(suppressive + synergistic)) <= 20),
                             aes(label = perturbation), size = 6 / .pt) +
    coord_fixed()

```


```{r, paged.print=FALSE}
n_nonadd_gene_df2 <- prep_data %>%
  mutate(category = case_when(
    diff2 < -0.15 ~ "suppressive",
    diff2 >  0.15 ~ "synergistic",
    TRUE ~ "additive"
  )) %>%
  filter(! single_pert) %>%
  count(perturbation, category) %>%
  pivot_wider(id_cols = perturbation, names_from = category, values_from = n, values_fill = 0) 

n_nonadd_gene_df2 %>%
  ggplot(aes(x = suppressive, y = synergistic)) +
    geom_point() +
    geom_abline() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(suppressive + synergistic)) <= 20),
                             aes(label = perturbation), size = 6 / .pt) +
    coord_fixed()

```


```{r, paged.print=FALSE}
perts <- c("BAK1", "BCL2L11", "ctrl")

sel_pert_dat <- prep_data %>%
  nest(.by = c(perturbation, perturbation_split), .key = "data")  %>%
  filter(map_lgl(perturbation_split, \(x) length(setdiff(x, perts)) == 0)) %>%
  unnest(data) %>%
  mutate(perturbation = str_replace_all(perturbation, perts[1], "A") |> str_replace_all(perts[2], "B") |> str_replace_all("\\+ctrl", "")) %>%
  transmute(perturbation, gene_name, ground_truth) %>%
  pivot_wider(id_cols = gene_name, names_from = perturbation, values_from = ground_truth) %>%
  mutate(error = `A+B` - (A + B - ctrl)) 

sel_pert_dat %>%
  ggplot(aes(x = `A+B`, y = A + B - ctrl)) +
    geom_point(aes(color = abs(error) > 0.15)) +
    geom_abline() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(abs(error))) <= 5), aes(label = gene_name))
  
```

```{r, paged.print=FALSE}
sel_ranks <- 1:20 # 21:40

sel_pert_dat %>%
  mutate(label = case_when(
    rank(desc(abs(error))) %in% sel_ranks ~ "selected",
    abs(error) > 0.15 ~ "signif",
    TRUE ~ "other"
  )) %>%
  # filter(label != "other") %>%
  ggplot(aes(x = `A+B` - ctrl, y = A + B - 2 * ctrl)) +
    geom_segment(aes(x = A - ctrl, y = B - ctrl, yend = A + B - 2 * ctrl, xend = `A+B` - ctrl, color = label), 
                 linewidth = 0.2,
                 arrow = arrow(type = "closed", length = unit(1, "mm"))) +
    geom_smooth(method = "lm", se = FALSE) +
    ggrepel::geom_text_repel(data = . %>% filter(label == "selected"), 
                             aes(label = gene_name), size = 6 / .pt) +
    geom_abline() +
    labs(x = "A - ctrl and AB - ctrl", y = "B - ctrl and A+B - 2 * ctrl")
    # geom_point(aes(x = A, y = B, color = abs(error) > 0.15)) +
```


```{r, paged.print=FALSE}
prep_data %>%
  nest(.by = c(perturbation, perturbation_split), .key = "data")  %>%
  filter(map_lgl(perturbation_split, \(x) length(setdiff(x, perts)) == 0)) %>%
  unnest(data) %>%
  mutate(perturbation = str_replace_all(perturbation, perts[1], "A") |> str_replace_all(perts[2], "B") |> str_replace_all("\\+ctrl", "")) %>%
  transmute(perturbation, gene_name, ground_truth) %>%
  pivot_wider(id_cols = gene_name, names_from = perturbation, values_from = ground_truth)  %>%
  transmute(gene_name, AB = `A+B`, A_delta = A - ctrl, B_delta = B - ctrl, ctrl_base = ctrl, A, B, ctrl) %>%
  pivot_longer(-gene_name, names_to = "perturbation", values_to = "expr")  %>%
  arrange(gene_name) %>%
  mutate(label = case_when(
    perturbation %in% c("A_delta", "B_delta", "ctrl_base") ~ "add",
    TRUE ~ perturbation
  )) %>% 
  mutate(label = factor(label, levels = c("AB", "add", "ctrl", "A", "B"))) %>%
  mutate(fill = ifelse(label == "add", perturbation, "other"),
         fill = factor(fill, c("ctrl_base", "A_delta", "B_delta", "other"))) %>%
  arrange(gene_name, fill) %>%
  mutate(height = cumsum(expr), .by = c(gene_name, label),
         lag_height = lag(height, default = 0)) %>%
  # inner_join(slice_max(sel_pert_dat, abs(error), n = 20) %>% dplyr::select(gene_name, error)) %>%
  inner_join(slice(sel_pert_dat %>% arrange(-abs(error)), sel_ranks) %>% dplyr::select(gene_name, error)) %>%
  mutate(gene_name = fct_reorder(gene_name, -abs(error))) %>%
  ggplot() +
    geom_hline(data = . %>% filter(label == "AB"), aes(yintercept = expr)) +
    geom_tile(aes(x = label, width = 0.5, y = (height + lag_height)/2, height = expr, fill = fill), 
              position = position_dodge2()) +
    facet_wrap(vars(gene_name), scales = "free_y") +
    labs(title = paste0("Double perturbation of A=", perts[1], " and B=", perts[2]))
  
  
```


```{r, paged.print=FALSE}
sel_pert_dat %>%
  ggplot(aes(x = A - ctrl, y = B - ctrl)) +
    geom_point(aes(color = error), size = 0.3) +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(abs(error))) <= 20), aes(label = gene_name), size = 6 / .pt) +
    lemur.utils::scale_color_de(qlimits = 0.01) +
    coord_fixed()
```


```{r, paged.print=FALSE}
sel_pert_dat %>%
  ggplot(aes(x = `A+B` - (A + B - ctrl), y = A - ctrl)) +
    geom_point()
```




```{r, paged.print=FALSE}
safe_seq <- function(from = 1, to = 1){
  if(to < from){
    integer(0L)
  }else{
    seq(from, to)
  }
}

slice_extremes <- function(.data, order_by, ..., n_front, n_back = n_front, prop, by = NULL){
  sel_ind_front <- safe_seq(1, n_front)
  sel_ind_back  <- rev(nrow(.data) - safe_seq(1, n_back) + 1)
  .data %>% arrange({{order_by}}) %>% slice(c(sel_ind_front, sel_ind_back))
}


sel_combs <- n_nonadd_gene_df2 %>%
  arrange(-(suppressive + synergistic)) %>%
  mutate(i = row_number()) %>%
  slice_extremes(n_front = 10) %>%
  # slice(c(1:10, ) %>%
  # slice_max(suppressive + synergistic, n = 10) %>%
  pull(perturbation)

# sel_combs <- n_nonadd_gene_df %>%
#   filter(str_detect(perturbation, "CEBP[ABE]\\+[^(ctrl)]") | str_detect(perturbation, "[^(ctrl)]\\+CEBP[ABE]")) %>%
#   pull(perturbation)


filter_combs <- tibble(perturbation = sel_combs) %>%
  mutate(split = str_split(perturbation, "\\+")) %>%
  mutate(combs = map(split, \(x) list(x, c(x[1], "ctrl"), c(x[2], "ctrl"), "ctrl")),
         labels = map(split, \(x) c("AB", "A", "B", "ctrl"))) %>%
  transmute(pert_group = perturbation, 
            combs = map(combs, \(x) map(x, sort, method = "radix")),
            labels) %>%
  unnest(c(combs, labels))

sel_pert_data2 <- prep_data %>%
  nest(.by = c(perturbation, perturbation_split), .key = "data")  %>%
  inner_join(filter_combs, by = c("perturbation_split" = "combs")) %>%
  unnest(data) %>%
  dplyr::select(pert_group, labels, gene_name, ground_truth) %>%
  pivot_wider(id_cols = c(gene_name, pert_group), names_from = labels, values_from = ground_truth) %>%
  mutate(error = `AB` - (A + B - ctrl)) %>%
  mutate(error2 = broom::augment(lm(`AB`-ctrl  ~ I(A - ctrl) + I(B - ctrl) - 1))$.resid, .by = pert_group) %>%
  mutate(error3 = broom::augment(lm(`AB`-ctrl  ~ I(A - ctrl + B - ctrl) - 1))$.resid, .by = pert_group) %>%
  mutate(pert_group = fct_reorder(pert_group, error, \(x) median(abs(x)))) 
```


```{r}
sel_pert_data2 %>%
  ggplot(aes(x = error, y = error2)) +
    geom_abline(linewidth = 0.3) +
    geom_point(size = 0.3) +
    facet_wrap(vars(pert_group))
```


```{r}
sel_pert_data2 %>%
  ggplot(aes(x = A - ctrl, y = B - ctrl)) +
    geom_abline() +
    geom_point(aes(color = error), size = 0.3) +
    lemur.utils::scale_color_de(qlimits = 0.01) +
    coord_fixed() +
    facet_wrap(vars(pert_group), nrow = 4)
```


```{r}
sel_pert_data2 %>%
  ggplot(aes(x = A - ctrl, y = B - ctrl)) +
    geom_abline() +
    geom_point(aes(color = error2), size = 0.3) +
    lemur.utils::scale_color_de(qlimits = 0.01) +
    coord_fixed() +
    facet_wrap(vars(pert_group), nrow = 4)
```

```{r}
sel_pert_data2 %>%
  # filter(abs(error) > 0.15) %>%
  ggplot() +
    geom_segment(aes(x = A - ctrl, y = B - ctrl, yend = A + B - 2 * ctrl, xend = `AB` - ctrl, alpha = abs(error)),
                 linewidth = 0.2,
                 arrow = arrow(type = "closed", length = unit(1, "mm"))) +
    geom_abline() +
    geom_smooth(aes(y = A + B - 2 * ctrl, x = `AB` - ctrl), method = "lm", se = FALSE) +
    labs(x = "A - ctrl and AB - ctrl", y = "B - ctrl and A+B - 2 * ctrl")  +
    coord_fixed() +
    scale_alpha_continuous() +
    facet_wrap(vars(pert_group), nrow = 2) +
    theme(legend.position = "bottom")
```



# All combinations

```{r, paged.print=FALSE}
all_combs <- tibble(perturbation = res$perturbation |> discard(\(x) str_detect(x, "ctrl")) |> unique()) %>%
  mutate(split = str_split(perturbation, "\\+")) %>%
  mutate(combs = map(split, \(x) list(x, c(x[1], "ctrl"), c(x[2], "ctrl"), "ctrl")),
         labels = map(split, \(x) c("AB", "A", "B", "ctrl"))) %>%
  transmute(pert_group = perturbation, 
            combs = map(combs, \(x) map(x, sort, method = "radix")),
            labels) %>%
  unnest(c(combs, labels))

sel_pert_data3 <- prep_data %>%
  nest(.by = c(perturbation, perturbation_split), .key = "data")  %>%
  inner_join(all_combs, by = c("perturbation_split" = "combs")) %>%
  unnest(data) %>%
  dplyr::select(pert_group, labels, gene_name, ground_truth) %>%
  pivot_wider(id_cols = c(gene_name, pert_group), names_from = labels, values_from = ground_truth) %>%
  mutate(error = `AB` - (A + B - ctrl)) %>%
  mutate(error2 = broom::augment(lm(`AB`-ctrl  ~ I(A - ctrl) + I(B - ctrl) - 1))$.resid, .by = pert_group) %>%
  mutate(error3 = broom::augment(lm(`AB`-ctrl  ~ I(A - ctrl + B - ctrl) - 1))$.resid, .by = pert_group) %>%
  mutate(pert_group = fct_reorder(pert_group, error, \(x) median(abs(x))))

sel_pert_data3
```

```{r}
sel_pert_data3 %>%
   mutate(category = case_when(
    error2 < -0.15 ~ "suppressive",
    error2 >  0.15 ~ "synergistic",
    TRUE ~ "additive"
  )) %>%
  count(pert_group, category) %>%
  pivot_wider(id_cols = pert_group, names_from = category, values_from = n, values_fill = 0)  %>%
  ggplot(aes(x = suppressive, y = synergistic)) +
    geom_point() +
    geom_abline() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(suppressive + synergistic)) <= 20),
                             aes(label = pert_group), size = 6 / .pt) +
    coord_fixed()

sel_pert_data3 %>%
  summarize(pos = sum(pmax(0, error2)),  neg = sum(pmin(0, error2)), .by = pert_group) %>%
  ggplot(aes(x = -neg, y = pos)) +
    geom_point() +
    geom_abline() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(pos - neg)) <= 20),
                             aes(label = pert_group), size = 6 / .pt) +
    coord_fixed()
```


Notes: 
- C3off72 is FOXL2NB (i.e, FOXL2 Neighbor)
- DLX2

```{r, paged.print=FALSE}
sel_pert_data3 %>%
  mutate(pert_group = fct_reorder(pert_group, error2, \(x) sum(abs(x)))) %>%
  nest(.by = pert_group, .key = "data") %>%
  slice_extremes(pert_group, n_front = 10) %>%
  unnest(data) %>%
  ggplot(aes(x = A - ctrl, y = B - ctrl)) +
    geom_abline() +
    geom_point(aes(color = error2), size = 0.3) +
    lemur.utils::scale_color_de(qlimits = 0.01) +
    coord_fixed() +
    facet_wrap(vars(pert_group), nrow = 4)
```

# Calculate alpha


```{r, paged.print=FALSE}

single_perts <- res %>%
  filter(method == "ground_truth" & seed == 1 & dataset == "norman") %>%
  filter(single_pert) %>%
  transmute(pert = str_remove(perturbation, "\\+ctrl"), prediction)

sim_alpha_df <- sel_pert_data3 %>%
  summarize(alpha = list(broom::tidy(lm(AB - ctrl ~ I(A + B - 2 * ctrl) - 1))  %>% select(estimate, std.error)), 
            mean_abs_error = mean(abs(error)),
            mean_abs_error2 = mean(abs(error2)),
            mean_abs_error3 = mean(abs(error2)),
            .by = pert_group) %>%
  unnest(alpha, names_sep = "_") %>%
  separate(pert_group, into = c("A", "B"), sep = "\\+", remove = FALSE) %>%
  left_join(single_perts %>% rename(pred_A = prediction), by = c("A"="pert")) %>%
  left_join(single_perts %>% rename(pred_B = prediction), by = c("B"="pert")) %>%
  mutate(dist = map2_dbl(pred_A, pred_B, \(a, b) sqrt(sum((a - b)^2))),
         cor = map2_dbl(pred_A, pred_B, \(a, b) cor(a, b) ))

sim_alpha_df %>%
  ggplot(aes(x = dist, y = alpha)) +
    geom_point(aes(color = mean_abs_error3)) +
    geom_smooth(method = "lm") +
    # ggrepel::geom_text_repel(data = . %>% filter(dist < 2.5 & alpha < 0.9), aes(label = pert_group), size = 6 / .pt) +
    ggrepel::geom_text_repel(data = . %>% filter(dist < 10 & dist > 5 & alpha < 0.8), aes(label = pert_group), size = 6 / .pt) +
    scale_color_viridis_c()

sim_alpha_df %>%
  ggplot(aes(x = 1-cor, y = alpha)) +
    geom_point(aes(color = mean_abs_error3)) +
    geom_smooth(method = "lm") +
    scale_x_log10() +
    # ggrepel::geom_text_repel(data = . %>% filter(dist < 2.5 & alpha < 0.9), aes(label = pert_group), size = 6 / .pt) +
    # ggrepel::geom_text_repel(data = . %>% filter(dist < 10 & dist > 5 & alpha < 0.8), aes(label = pert_group), size = 6 / .pt) +
    scale_color_viridis_c()
```


```{r, paged.print=FALSE}
sim_alpha_df %>%
  mutate() %>%
  ggplot(aes(x = alpha, y = mean_abs_error3)) +
    geom_point() +
    geom_smooth(method = "lm")
```


```{r, paged.print=FALSE}
sim_alpha_df %>% 
  arrange(desc(cor)) %>%
  print(n = 30)
```


```{r, paged.print=FALSE}
dist2 <- function(x, y){
  sqrt(sum((x - y)^2))
}

sel_pert_data3 %>%
  mutate(pred1 = A + B - ctrl,
         pred2 = broom::augment(lm(AB - ctrl ~ I(A - ctrl) + I(B - ctrl) - 1))$.fitted + ctrl, .by = pert_group) %>%
  summarize(cor1 = cor(AB - ctrl, pred1 - ctrl),
            cor2 = cor(AB - ctrl, pred2 - ctrl), .by = pert_group) %>%
  ggplot(aes(x = cor1, y = cor2)) +
    geom_point() +
    ggrepel::geom_text_repel(data = . %>% filter(rank(desc(abs(cor1 - cor2))) < 5), aes(label = pert_group), size = 6/.pt) +
    ggrepel::geom_text_repel(data = . %>% filter(rank(cor1) < 5), aes(label = pert_group), size = 6/.pt) +
    geom_abline() +
    stat_summary(geom = "hline", fun = mean, aes(x = 1, yintercept = ..y..), color = "red", linetype = "dashed") +
    stat_summary(geom = "vline", fun = mean, aes(y = 1, xintercept = ..x..), color = "red", linetype = "dashed", orientation = "y") +
    coord_fixed()
```

```{r, paged.print=FALSE}
sel_pert_data3 %>%
  mutate(pred1 = A + B - ctrl) %>%
  summarize(cor = cor(AB - ctrl, pred1 - ctrl), .by = pert_group) %>%
  arrange(cor)
```


```{r, paged.print=FALSE}
sim_alpha_df2 <- sel_pert_data3 %>%
  summarize(alpha = list(broom::tidy(lm(AB - ctrl ~ I(A - ctrl)  + I(B - ctrl) - 1))  %>% select(term, estimate, std.error)), 
            mean_abs_error = mean(abs(error)),
            mean_abs_error2 = mean(abs(error2)),
            .by = pert_group) %>%
  unnest(alpha, names_sep = "_") %>%
  mutate(alpha_term = str_extract(alpha_term, "[AB]")) %>%
  pivot_wider(id_cols = c(pert_group, mean_abs_error, mean_abs_error2), names_from = alpha_term, values_from = c(alpha_estimate, alpha_std.error), names_glue = "{alpha_term}_{.value}") %>%
  dplyr::rename_with(\(x) str_remove(x, "_alpha"), matches("[AB]_alpha_")) %>%
  separate(pert_group, into = c("A", "B"), sep = "\\+", remove = FALSE) %>%
  left_join(single_perts %>% rename(pred_A = prediction), by = c("A"="pert")) %>%
  left_join(single_perts %>% rename(pred_B = prediction), by = c("B"="pert")) %>%
  mutate(dist = map2_dbl(pred_A, pred_B, \(a, b) sqrt(sum((a - b)^2))),
         cor = map2_dbl(pred_A, pred_B, \(a, b) cor(a, b) ))

sim_alpha_df2
```


```{r, paged.print=FALSE}
sim_alpha_df2 %>%
  ggplot(aes(x = A_estimate, y = B_estimate)) +
    geom_point(aes(color = cor)) +
    scale_color_viridis_c()
```

```{r, paged.print=FALSE}
pivot_wider2matrix <- function(.data, rows_from, columns_from, values_from, rowname_sep = "-", colname_sep = "-", ...){
  wide_df <- pivot_wider(.data, id_cols = {{rows_from}}, names_from = {{columns_from}}, values_from = {{values_from}}, ..., names_sep = colname_sep) |>
    unite("..rownames", {{rows_from}}, sep = rowname_sep)
  row_names <- wide_df$..rownames
  mat <- as.matrix(dplyr::select(wide_df, -..rownames))
  rownames(mat) <- row_names
  mat
}

error_mat <- sel_pert_data3 %>%
  pivot_wider2matrix(gene_name, pert_group, error2)

pca <- lemur:::pca(error_mat, n = 2)
tibble(pert_group = colnames(error_mat), emb = t(pca$embedding)) %>%
  ggplot(aes(x = emb[,1], y = emb[,2])) +
    geom_point() +
    coord_fixed()

tibble(gene = rownames(error_mat), loading = pca$coordsystem) %>%
  arrange(-apply(loading, 1, \(x) sum(x^2)))
```

